### ISSUE TITLE
Building pieces per clan showing clan size

### ISSUE THREAD

**Issue by WilliamStam** [Sixxgunz/conanexiles_scripts#1]
hiya. i added this to my game DB. thought i would share

````
CREATE VIEW `Building_Pieces_Members` AS 
SELECT Owner, sum(Pieces) as Pieces, 
	(SELECT CASE WHEN COUNT(name) > 1 THEN COUNT(name) else 1 END FROM guilds AS g
	INNER JOIN characters c on c.guild = g.guildId
	WHERE g.name  = structure_locations.Owner 
) as Members
FROM structure_locations GROUP BY Owner ORDER BY sum(Pieces) DESC
````

for March2018_CustomViewCollection.sql

**Comment by Sixxgunz** [comment]
I just now noticed this, this is actually displayed in the structure locations view also.

**Comment by WilliamStam** [comment]
when i was using the script regularly it just showed "total pieces per clan" not / the clan size for something. anyways thanks!
